### ISSUE TITLE
[사용자] 게시글 작성 화면 개발

### ISSUE THREAD

**Issue by seiyoon** [kookmin-sw/capstone-2023-09#10]
## Description
자유 / 도움주기 / 도움받기 게시글 작성 페이지

## To-do
- [x] UI 개발
- [x] 모든 내용 입력 시 버튼 활성화
- [x] 카테고리 구현
- [x] 보유 타임페이, 지급 타임페이
- [x] 페이지 이동 버튼 구현

**Comment by seiyoon** [comment]
카테고리 태그랑 타임페이를 recoil 써서 입력한 값이 남아있음. 그거 처리해야함..
