### ISSUE TITLE
[사용자] 문의 기능 연결

### ISSUE THREAD

**Issue by seiyoon** [kookmin-sw/capstone-2023-09#107]
## Description
/inquire 화면 기능 연결

## To-do
- [ ] 문의 등록 기능
- [ ] 문의 조회 기능
- [ ] 문의 삭제 기능
