### ISSUE TITLE
[사용자] 게시글 조회 기능 연결

### ISSUE THREAD

**Issue by seiyoon** [kookmin-sw/capstone-2023-09#110]
## Description
/post 화면 기능 연결

## To-do
- [ ] 게시글 조회 기능 연결
- [ ] 게시글 수정 기능 연결
- [ ] 게시글 삭제 기능 연결
- [ ] 게시글 신고 기능 연결
   
- [ ] 게시글 댓글 등록 기능 연결
- [ ] 게시글 댓글 수정 기능 연결
- [ ] 게시글 댓글 삭제 기능 연결
- [ ] 게시글 댓글 신고 기능 연결
   
- [ ] 게시글 사용자별 다른 버튼 보이게
- [ ] 게시글 지원자 목록 조회 기능 연결
