### ISSUE TITLE
[사용자] 마이페이지 화면 개발

### ISSUE THREAD

**Issue by JinLee25154** [kookmin-sw/capstone-2023-09#13]
## Description
사용자 마이페이지 화면 개발

## To-do
- [x] 사용자 프로필 이미지 띄우기
- [x] 사용자 닉네임 띄우기
- [x] 사용자 고유 번호 띄우기
- [x] 사용자 타임페이 보유량 띄우기
- [x] 마이페이지 수정 버튼
- [x] 활동기록, 신고기록, 문의하기, 즐겨찾기 페이지 이동 버튼
