### ISSUE TITLE
[사용자, 관리자] 봉사활동 인증서 관련 화면 UI 추가

### ISSUE THREAD

**Issue by iioo3356** [kookmin-sw/capstone-2023-09#150]
## Description
[기획서 링크](https://docs.google.com/presentation/d/1PVlaLM_ic0tgSZNG3l5Dyc9bYUtFTpUXC7Q0Gkc9rdo/edit#slide=id.g230a43720be_0_17)
[피그마 링크](https://www.figma.com/file/VgaJP6q5Fygk1v46pwOoqR/TIMEPAY?node-id=1300-132&t=VTMk0leD1ZEJ0gG1-4)
봉사활동 시간을 지급하고, 지급받은 인증서를 확인할 수 있는 화면.
## To-do
- [ ] 기관 회원을 위한 로그인, 회원가입, 마이페이지 추가
- [ ] 기존 게시글 작성 화면을 이용해서 봉사활동 지급 게시글 작성 화면 추가
- [ ] 홈화면, 검색화면, 게시글 조회 화면에 봉사활동 지급 게시글만 볼 수 있는 검색 옵션 추가, 작성자의 타입(일반, 기관, 봉사활동 기관)에 따라 화면 수정, 봉사활동 지급 게시글일 때 뱃지 추가
- [ ] 봉사활동 인증서 지급 메뉴 추가
- [ ] 봉사활동 기록 메뉴 추가
- [ ] 관리자 사이트에서 기관 회원 관리 메뉴 추가
- [ ] 관리자 사이트 회원 관리 메뉴 - 메뉴명 변경, 관련된 컬럼(총 봉사시간, 활동기록 화면에 봉사활동 지급 게시글 여부 추가)
- [ ] 관리자 사이트 게시글 관리 메뉴 - 봉사활동 지급 게시글 여부 추가, 봉사활동 지급 게시글만 볼 수 있는 검색값 추가, 인증서 발급 현황을 볼 수 있는 모달 추가
