### ISSUE TITLE
[사용자] 타 유저 프로필 조회 화면 UI 개발

### ISSUE THREAD

**Issue by iioo3356** [kookmin-sw/capstone-2023-09#21]
## Description
타 유저의 기본정보(사진, 닉네임 등)와 활동 기록을 조회할 수 있고 해당 유저를 신고할 수 있는 드로어 화면 개발
## To-do
- [x] 드로어 컴포넌트 개발
- [x] 기본 정보 조회 섹션 개발
- [x] 활동 기록 조회 섹션 개발
