### ISSUE TITLE
[사용자] 게시글 조회 화면 UI 개발

### ISSUE THREAD

**Issue by seiyoon** [kookmin-sw/capstone-2023-09#26]
## Description
홈 화면에서 게시글 클릭 시 보이는 화면

## To-do
- [x] 단계별 버튼 구현하기
- [x] 즐겨찾기 하트 만들기
- [x] 수정 페이지
- [x] 삭제 기능
- [x] 댓글 UI 구현
