### ISSUE TITLE
[관리자] 회원관리 - 회원 삭제 화면 개발 (보류)

### ISSUE THREAD

**Issue by JinLee25154** [kookmin-sw/capstone-2023-09#28]
## Description
관리자 회원관리 - 회원 삭제 화면 개발

## To-do
- [ ] 회원 삭제 관련 설명문
- [ ] 삭제할 회원 수
- [ ] 삭제할 회원의 회원번호/이름/타임페이 보유량
- [ ] 취소 버튼 (전 화면으로 돌아가기)
- [ ] 삭제 버튼
