### ISSUE TITLE
[사용자] 즉석 매칭 기능 화면, 기능 연결

### ISSUE THREAD

**Issue by iioo3356** [kookmin-sw/capstone-2023-09#283]
## Description
사용자가 오프라인 상에서 다른 사용자와 활동 후 바로 활동을 기록할 수 있는 기능 추가
[디자인](https://www.figma.com/file/VgaJP6q5Fygk1v46pwOoqR/TIMEPAY?type=design&node-id=1596-347&t=nDuU58iM20SY3ugH-4)
[api 명세서](https://docs.google.com/spreadsheets/d/1zn8YgCUwtqjEihCyjAaIzAJCnis5H4l8ehFdGGGp9Pc/edit#gid=1526989388)

## To-do
- [x] 작성 버튼에 즉석활동 추가
- [x] 즉석 활동 작성 화면 추가
- [x] 즉석 활동 작성 화면으로 가는 링크를 가진 QR 추가
- [x] api 연결
