### ISSUE TITLE
[관리자] 회원관리 - 유저별 활동 목록 개발

### ISSUE THREAD

**Issue by JinLee25154** [kookmin-sw/capstone-2023-09#29]
## Description
관리자 회원관리 - 유저별 활동 목록 개발

## To-do
- [x] Tab - 게시글, 댓글, 신고받은 내역, 신고한 내역
- [x] 1. 게시글: 게시글 번호/작성 날짜/유형/현재 상태/설정활동시간/실제활동시간/제목
- [x] 2. 댓글: 댓글 번호/작성 날짜/지원 여부/확정 여부/내용
- [x] 3. 신고받은 내역: 신고 번호/신고자/신고 사유/게시글 번호/댓글 번호
- [x] 4. 신고한 내역: 신고 번호/신고받은 유저/신고 사유/게시글 번호/댓글 번호
