### ISSUE TITLE
[사용자] [관리자] 공통 코드 개발

### ISSUE THREAD

**Issue by iioo3356** [kookmin-sw/capstone-2023-09#30]
## Description
프론트엔드 개발 시 협의된 사항으로 공통 코드를 만들어 공유
## To-do
- [x] CRA, typescript 사용
- [ ] 프리텐다드 글꼴 추가 및 적용
- [x] ant design + emotion, React Query, Recoil 사용
- [x] 베이스 레이아웃(헤더, 푸터) 추가
- [x] prettier, eslint 적용
- [x] master 브랜치로 공유
