### ISSUE TITLE
[사용자] 홈화면 UI 개발

### ISSUE THREAD

**Issue by iioo3356** [kookmin-sw/capstone-2023-09#8]
## Description
게시글 유형, 카테고리 별로 게시글들을 조회하는 무한 스크롤 화면
## To-do
- [x] 단순화한 게시글 컴포넌트 추가
- [x] 유형, 카테고리 팝업 컴포넌트 추가 및 적용
- [x] 푸터 홈화면 버튼과 링크 연결
